controllers/HomeController.php
<?php
/**
 * @link http://zenothing.com/
 */

namespace app\controllers;


use app\behaviors\NoTokenValidation;
use app\models\Message;
use app\modules\invoice\models\Invoice;
use app\models\User;
use app\helpers\SQL;
use Yii;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;

/**
 * @author Taras Labiak <kissarat@gmail.com>
 */
class HomeController extends Controller {

    public function behaviors() {
        return [
            'no_csrf' => [
                'class' => NoTokenValidation::class,
                'only' => ['index'],
            ]
        ];
    }

    public function actionIndex() {
        if (static::tryLogin()) {
            Message::show();
        }

        return $this->render('index', [
            'statistics' => $this->renderPartial('statistics', ['statistics' => static::statistics()]),
        ]);
    }

    public static function tryLogin() {
        if (Yii::$app->user->getIsGuest() && isset($_POST['auth'])
            && $user = User::findOne(['auth' => $_POST['auth']])) {
            Yii::$app->user->login($user);
        }
        return !Yii::$app->user->getIsGuest();
    }

    public function actionStatistics() {
        static::tryLogin();
        return $this->render('statistics', ['statistics' => static::statistics()]);
    }

    public function actionError() {
        $exception = Yii::$app->getErrorHandler()->exception;
        $message = $exception->getMessage();
        if ($exception instanceof ForbiddenHttpException) {
            $message = $message ? Yii::t('app', $message) : Yii::t('app', 'Forbidden');
        }
        if ($message) {
            Yii::$app->session->setFlash('error', $message);
        }
        return $this->render('error', [
            'exception' => $exception
        ]);
    }

    public function actionBanner() {
        return $this->render('banner');
    }

    public static function statistics() {
        $started = strtotime(SQL::queryCell('SELECT "time" FROM "journal" WHERE id = 1'));
        $invested = (int) SQL::queryCell('SELECT count(*) FROM "node"');
        return [
            'Started' => date('d-m-Y', $started),
            'Running days' => floor((time() - $started)/(3600 * 24)),
            'Users' => User::find()->count(),
            'Total deposited' => Invoice::find()->where(['or',
                ['status' => 'success'],
                ['status' => 'delete']
            ])->andWhere('amount > 0')->sum('amount'),
            'Total withdraw' => - Invoice::find()->where(['or',
                ['status' => 'success'],
                ['status' => 'delete']
            ])->andWhere('amount < 0')->sum('amount'),
            'Number of investments' => $invested
        ];
    }
}

controllers/UserController.php
<?php
/**
 * @link http://zenothing.com/
 */

namespace app\controllers;

use app\behaviors\Access;
use app\behaviors\Journal;
use app\models\Login;
use app\models\Message;
use app\models\Password;
use app\models\Record;
use app\models\ResetRequest;
use app\helpers\SQL;
use Yii;
use app\models\User;
use app\models\search\User as UserSearch;
use yii\base\InvalidParamException;
use yii\filters\VerbFilter;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * @author Taras Labiak <kissarat@gmail.com>
 */
class UserController extends Controller
{
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['post'],
                ],
            ],

            'access' => [
                'class' => Access::class,
                'plain' => ['index', 'view', 'update'],
                'manager' => ['complete', 'account'],
                'admin' => ['delete']
            ]
        ];
    }

    public function actionIndex() {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'model' => Yii::$app->user->identity->isManager() ? null : Yii::$app->user->identity
        ]);
    }

    public function actionView($name = null) {
        if (!$name && Yii::$app->user->isGuest) {
            throw new InvalidParamException();
        }

        $model = $name ? $this->findModel($name) : Yii::$app->user->identity;
        if (Yii::$app->user->isGuest
            || (!Yii::$app->user->identity->isManager() && Yii::$app->user->identity->name != $model->name)) {
            throw new ForbiddenHttpException();
        }

        if ($model->name == Yii::$app->user->identity->name) {
            Message::show();
        }

        return $this->render('view', [
            'model' => $model,
        ]);
    }

    public function actionCreate() {
        $model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'name' => $model->name]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    public function actionUpdate($name) {
        $model = $this->findModel($name);

        if ($model->name != Yii::$app->user->identity->name && !Yii::$app->user->identity->isAdmin()) {
            throw new ForbiddenHttpException('Forbidden');
        }

        if ($model->load(Yii::$app->request->post())) {
            if (!Yii::$app->user->identity->isAdmin()) {
                if ($model->isAttributeChanged('email', false)) {
                    $model->generateCode();
                    $url = Url::to(['email', 'code' => $model->code], true);
                    $model->sendEmail([
                        'subject' => Yii::$app->params['site']['name'] . ' ' . Yii::t('app', 'Email confirmation'),
                        'content' => Yii::t('app', 'To confirm your email click on the <a href="{url}">link</a>', [
                            'url' => $url,
                        ])
                    ]);
                    $model->setBundle(['email' => $model->email]);
                    $model->email = $model->getOldAttribute('email');
                    Yii::$app->session->setFlash('info', Yii::t('app', 'The new email address will be changed after you confirm it'));
                }
                if ($model->isAttributeChanged('perfect', false)) {
                    $model->perfect = $model->getOldAttribute('perfect');
                    Yii::$app->session->setFlash('error', Yii::t('app', 'Wallet can change admin only'));
                }
            }

            if ('Europe/Moscow' == $model->timezone) {
                $model->timezone = null;
            }

            foreach(['skype', 'country', 'phone', 'forename', 'surname'] as $name) {
                if (empty($model->$name)) {
                    $model->$name = null;
                }
            }

            if (Yii::$app->user->identity->name == $model->name && $model->isAttributeChanged('timezone', false)) {
                $_SESSION['timezone'] = $model->timezone;
            }

            if ($model->save()) {
                return $this->redirect(['view', 'name' => $model->name]);
            }
        }

        if (!$model->timezone) {
            $model->timezone = 'Europe/Moscow';
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionDelete($name) {
        $this->findModel($name)->delete();
        return $this->redirect(['index']);
    }

    /**
     * @param string $name
     * @return User
     * @throws NotFoundHttpException
     */
    protected function findModel($name) {
        if (($model = User::findOne(['name' => $name])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionSignup($ref_name = null) {
        $model = new User([
            'scenario' => 'signup'
        ]);
        if (!$ref_name && Yii::$app->session->has('ref_name')) {
            $ref_name = Yii::$app->session->get('ref_name');
        }
        if ($ref_name) {
            $model->ref_name = $ref_name;
            if (!Yii::$app->session->has('ref_name')) {
                Yii::$app->session->set('ref_name', $ref_name);
            }
        }
        if (preg_match('|U\w{7}|', $model->name)) {
            $model->addError('name', Yii::t('app', Yii::t('app', 'Username cannot be in the format of Perfect Money wallet')));
        }
        elseif ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->generateAuthKey();
            $model->status = User::PLAIN;
            if (!$model->ref_name) {
                $model->ref_name = 'Alex-Shild123';
            }
            if ($model->save(false)) {
                Yii::$app->user->login($model);
                return $this->redirect(['user/view']);
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionLogin() {
        $model = new Login();

        if ($model->load(Yii::$app->request->post())) {
            $user = $model->getUser();
            if ($user) {
                if (empty($user->hash)) {
                    Yii::$app->session->setFlash('error', Yii::t('app',
                        Yii::t('app', 'Your account is not activated. Check your email')));
                }
                else {
                    $can = $user->canLogin();
                    if ($can && $user->validatePassword($model->password)) {
                        if ($user->status > 0) {
                            if (empty($user->auth)) {
                                $user->generateAuthKey();
                                $user->save();
                            }

                            if ('admin' == Yii::$app->layout && !$user->isManager()) {
                                Yii::$app->session->addFlash('error', Yii::t('app', 'You cannot manage site'));
                            }
                            elseif (Yii::$app->user->login($user, $model->remember ? $user->duration * 60 : 0)) {
                                if ('admin' == Yii::$app->layout) {
                                    return $this->redirect(['/home/statistics']);
                                }
                                else {
                                    return $this->redirect(['view']);
                                }
                            }
                            else {
                                Yii::$app->session->addFlash('error', Yii::t('app', 'Something wrong happened'));
                            }
                        } else {
                            Yii::$app->session->setFlash('error', Yii::t('app', Yii::t('app', 'Your account is blocked')));
                        }
                    } else {
                        Journal::write('user', 'login_fail', $user->id);
                        if ($can) {
                            Yii::$app->session->setFlash('error', Yii::t('app', 'Invalid username or password'));
                        } else {
                            $record = Record::find()->where([
                                'object_id' => $user->id,
                                'event' => 'login_fail'
                            ])->orderBy(['time' => SORT_DESC])->one();
                            Yii::$app->session->setFlash('error',
                                Yii::t('app', 'You have exceeded the maximum number of login attempts, you will be able to enter after {time}', [
                                    'time' => $record->time
                                ]));
                        }
                    }
                }
            }
            else {
                Yii::$app->session->setFlash('error', Yii::t('app', 'Invalid username or password'));
            }
        }

        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout() {
        Yii::$app->user->logout();
        return $this->redirect(['home/index']);
    }

    public function actionEmail($code) {
        /** @var User $user */
        if (!Yii::$app->user->isGuest && Yii::$app->user->identity->isAdmin()) {
            $user = User::findOne(['name' => $code]);
        }
        else {
            $user = preg_match('|^[\w\-_]{64}$|', $code) ? User::findOne(['code' => $code]) : null;
        }
        if ($user) {

views/user/_form.php
<?php
/**
 * @link http://zenothing.com/
 */

use app\models\User;
use app\widgets\Ext;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\User */

function submit($label) {
    return Html::submitButton($label, ['class' => 'btn btn-success']);
}

echo Ext::stamp();

$form = ActiveForm::begin();

if ($model->ref_name && $model->isNewRecord): ?>
    <div class="form-group">
        <?= Yii::t('app', 'Referral') . ': ' . $model->ref_name; ?>
    </div>
    <?= Html::activeHiddenInput($model, 'ref_name') ?>
<?php endif;

if ($model->isNewRecord) {
    echo $form->field($model, 'name');
}

echo $form->field($model, 'email');
echo $form->field($model, 'skype');

if ('signup' == $model->scenario) {
    echo $form->field($model, 'password')->passwordInput();
    echo $form->field($model, 'repeat')->passwordInput();
}

if (!Yii::$app->user->isGuest && Yii::$app->user->identity->isAdmin()) {
    echo $form->field($model, 'account');
    echo $form->field($model, 'status')->dropDownList(User::statuses());
}

if (!$model->isNewRecord) {
    echo $form->field($model, 'phone');
    echo $form->field($model, 'forename');
    echo $form->field($model, 'surname');
}

if ($model->isNewRecord || Yii::$app->user->identity->isAdmin()) {
    echo $form->field($model, 'perfect');
}
else {
    echo Html::tag('div', Yii::t('app', 'To change a wallet you need <a href="{url}">write to admin</a>', [
        'url' => Url::to(['feedback/feedback/create', 'template' => 'wallet'])
    ]),
        ['class' => 'form-group']);
}

echo Html::tag('div', '* ' . Yii::t('app', 'Required fields'), ['class' => 'form-group']);

if (Yii::$app->user->isGuest) {
    echo submit(Yii::t('app', 'Signup'));
}
else {
    if ($model->isNewRecord) {
        echo submit(Yii::t('app', 'Create'));
    }
    else {
        echo submit(Yii::t('app', 'Update'));
    }
}

ActiveForm::end();

views/user/_search.php
<?php
/**
 * @link http://zenothing.com/
 */

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'email') ?>

    <?= $form->field($model, 'hash') ?>

    <?= $form->field($model, 'auth') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/account.php
<?php
/**
 * @link http://zenothing.com/
 */
use yii\helpers\Html;

?>
<div class="account">
    <h1><?= Yii::t('app', 'Accounts') ?></h1>
    <table class="table">
        <?php
        foreach($model as $key => $value) {
            echo Html::tag('tr',
                Html::tag('td', Yii::t('app', $key)) .
                Html::tag('td', $value)
            );
        }
        ?>
    </table>
</div>

views/user/create.php
<?php
/**
 * @link http://zenothing.com/
*/

use yii\authclient\widgets\AuthChoice;
use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = Yii::$app->user->isGuest ? Yii::t('app', 'Signup') : Yii::t('app', 'Create User');
?>
<div class="regpic"></div>
<div class="user-create">
    <div class="regbg">
    <table>
        <tr>
            <td class="regtc"></td>
            <td class="regf">
    <h1 class="bagatelle"><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
            </td>
            <td class="regtr"></td>
        </tr>
    </table>
        </div>
</div>

views/user/index.php
<?php
/**
 * @link http://zenothing.com/
 */

use app\models\User;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\User */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', Yii::$app->user->identity->isManager() ? 'Users' : 'Sponsors');

$columns = [
    [
        'attribute' => 'name',
        'format' => 'html',
        'value' => function($model) {
            return Html::a($model->name, ['view', 'name' => $model->name]);
        }
    ],
    'account',
    [
        'attribute' => 'perfect',
        'label' => Yii::t('app', 'Wallet')
    ],
];

if (!Yii::$app->user->getIsGuest() && Yii::$app->user->identity->isAdmin()) {
    $columns[] = 'email:email';
    $columns[] = 'skype';
    $columns[] = [
        'format' => 'html',
        'contentOptions' => ['class' => 'action'],
        'value' => function($model) {
            return implode(' ', [
                Html::a('', ['update', 'name' => $model->name], ['class' => 'glyphicon glyphicon-pencil']),
//                Html::a('', ['delete', 'id' => $model->id], ['class' => 'glyphicon glyphicon-trash'])
            ]);
        }
    ];
}
?>
<div class="user-index">
    <?php
    if ($model) {
        require 'panel.php';
    }
    ?>

    <div>
        <h1 class="bagatelle"><?= Html::encode($this->title) ?></h1>
        <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

        <p>
            <?php
            if (Yii::$app->user->identity->isAdmin()) {
                echo Html::a(Yii::t('app', 'Create User'), ['create'], ['class' => 'btn btn-success']);
            }
            ?>
        </p>

        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'columns' => $columns,
        ]); ?>
    </div>
</div>

views/user/journal.php
<?php
/**
 * @link http://zenothing.com/
*/

/**
 * @var app\models\Record $record
 */

use app\models\User;

$info = $record->info;
if (!$info) {
    echo '';
}
elseif (isset($info['status'])) {
    echo Yii::t('app', 'Status') . ': ' . User::statuses()[$info['status']];
}
elseif (isset($info['account'])) {
    echo Yii::t('app', 'Account') . ': ' . $info['account'];
}
else {
    $key = key($info);
    echo "$key: " . $info[$key];
}

views/user/login.php
<?php
/**
 * @link http://zenothing.com/
*/

use app\widgets\Ext;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Login */
/* @var $form ActiveForm */

$this->title = Yii::t('app', 'Login');
if ('admin' == Yii::$app->layout) {
    $this->title = Yii::t('app', 'Admin Panel') . ': ' . $this->title;
}
?>
<div class="user-login">
    <div class="regbg">
    <?= Ext::stamp() ?>
    <h1 class="bagatelle"><?= $this->title ?></h1>
    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name') ?>
    <?= $form->field($model, 'password')->passwordInput() ?>
    <?= $form->field($model, 'remember')->checkbox() ?>

    <?php if ('main' == Yii::$app->layout): ?>
    <div class="form-group">
        <?= Yii::t('app', 'You can recover <a href="{url}">your password</a>', [
            'url' => Url::to(['request']),
        ]); ?>
    </div>
    <?php endif ?>

    <?= Html::submitButton(Yii::t('app', 'Login'), ['class' => 'btn btn-primary']) ?>
    <?php ActiveForm::end(); ?>
        </div>
</div><!-- user-login -->

views/user/panel.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;

$social_url = 'http://' . $_SERVER['HTTP_HOST'];

function addtomany($network) {
    return "http://www.addtoany.com/add_to/$network?" . http_build_query([
        'linkname' => Yii::$app->name,
        'linkurl' => 'http://' . $_SERVER['HTTP_HOST']
    ]);
}

if (!Yii::$app->user->getIsGuest()):
    ?>
    <div id='cssmenu'>
        <ul>
            <li> <?=  Html::a(Yii::t('app', 'Opened Deposits'),
                    ['/bank/node/index', 'user' => $model->name], ['class' => 'btn btn-primary']) ?></li>
            <li> <?= Html::a(Yii::t('app', 'Income'),
                    ['/bank/income/index', 'user' => $model->name], ['class' => 'btn btn-primary']) ?></li>
            <li> <?= Html::a(Yii::t('app', 'Advertisement'), ['/home/banner'], ['class' => 'btn btn-primary']) ?></li>
            <?php
            if (!Yii::$app->user->isGuest) {
                if ($model->name == Yii::$app->user->identity->name || Yii::$app->user->identity->isAdmin()) {
                    echo Html::tag('li', Html::a(Yii::t('app', 'Change Password'),
                        ['/user/password', 'name' => $model->name], ['class' => 'btn btn-warning']));
                }
                ?>
                <?php
                if (Yii::$app->user->identity->isManager()) {
                    echo Html::tag('li', Html::a(Yii::t('app', 'Inform'),
                        ['/message/create', 'user' => $model->name], ['class' => 'btn btn-primary']));
                }
                ?>
                <li> <?= Html::a(Yii::t('app', 'Update'), ['/user/update', 'name' => $model->name], ['class' => 'btn btn-primary']) ?></li>
                <?php

                if ($model->name == Yii::$app->user->identity->name) {
                    echo Html::tag('li', Html::a(Yii::t('app', 'Sponsors'),
                        ['index'], ['class' => 'btn btn-primary']));
                }

                echo Html::tag('li', implode("\n", [
                    Html::a(Html::img('/images/vkontakte.png', ['alt' => '?????????']),
                        "https://vk.com/share.php?" . http_build_query(['url' => $social_url])),
                    Html::a(Html::img('/images/facebook.png', ['alt' => 'Facebook']),
                        'https://www.facebook.com/sharer.php?' . http_build_query([
                            's' => 100,
                            'p[url]' => $social_url
                        ])),
                    Html::a(Html::img('/images/odnoklassniki.png', ['alt' => '?????????????']),
                        addtomany('odnoklassniki')),
                    Html::a(Html::img('/images/twitter.png', ['alt' => 'Twitter']),
                        'https://twitter.com/intent/tweet?' . http_build_query(['url' => $social_url])),
                    ''
                ]));
                if (Yii::$app->user->identity->isAdmin()) {
                    if (empty($model->hash)) {
                        echo Html::tag('li', Html::a(Yii::t('app', 'Activate'), ['/user/email', 'code' => $model->name], ['class' => 'btn btn-primary']));
                    }
                    echo Html::tag('li', Html::a(Yii::t('app', 'Delete'), ['/user/delete', 'name' => $model->name
                    ], [
                        'class' => 'btn btn-danger',
                        'data' => [
                            'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                            'method' => 'post',
                        ],
                    ]));
                }
                elseif ($model->name == Yii::$app->user->identity->name) {
                    echo Html::tag('li', implode("\n", [
                        Html::beginForm('https://perfectmoney.is/api/step1.asp', 'POST'),
                        Html::hiddenInput('PAYEE_ACCOUNT', Yii::$app->perfect->wallet),
                        Html::textInput('PAYMENT_AMOUNT', 20, ['size' => 3]),
                        Html::hiddenInput('PAYEE_NAME', Yii::$app->name),
                        Html::hiddenInput('PAYMENT_UNITS', 'USD'),
                        Html::hiddenInput('PAYMENT_URL', Url::to(['/invoice/invoice/success'], true)),
                        Html::hiddenInput('NOPAYMENT_URL', Url::to(['/invoice/invoice/fail'], true)),
                        Html::hiddenInput('BAGGAGE_FIELDS', 'USER_NAME'),
                        Html::hiddenInput('USER_NAME', Yii::$app->user->identity->name),
                        Html::button(Yii::t('app', 'Pay'), [
                            'name' => 'PAYMENT_METHOD',
                            'type' => 'submit',
                            'class' => 'btn btn-primary'
                        ]),
                        Html::endForm()
                    ]));
                }
            }
            ?>
        </ul>
    </div>
<?php
endif;

views/user/password.php
<?php
/**
 * @link http://zenothing.com/
 */

use app\widgets\Ext;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var $this yii\web\View
 * @var $message string
 * @var $model app\models\Password
 * @var $form ActiveForm
 * @var $user app\models\User
 */

$reset = !$model || 'reset' == $model->scenario;
$this->title = Yii::t('app', $reset ? 'Reset Password' : 'Set Password');
if (!$reset) {
    if (!Yii::$app->user->isGuest && Yii::$app->user->identity->isManager()) {
        $this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
    }
    $this->params['breadcrumbs'][] = ['label' => $model->user_name, 'url' => ['view', 'name' => $model->user_name]];
    $this->params['breadcrumbs'][] = Yii::t('app', 'Password');
}

if ($message):
    echo "<div class=\"alert alert-danger\">$message</div>";
else:
    ?>
    <div class="user-password">
        <?= Ext::stamp() ?>

        <?php
        if ($user) {
            echo Yii::$app->view->render('panel', [
                'model' => $user
            ]);
        }
        ?>

        <div class="center">
            <h1><?= $this->title ?></h1>
            <?php $form = ActiveForm::begin(); ?>

            <?php if (!$reset) {
                echo $form->field($model, 'password')->passwordInput();
            }
            elseif (!Yii::$app->user->isGuest && Yii::$app->user->identity->isAdmin()) {
                echo Html::hiddenInput('name', $model->user_name);
            }
            ?>
            <?= $form->field($model, 'new_password')->passwordInput() ?>
            <?= $form->field($model, 'repeat_password')->passwordInput() ?>

            <div class="form-group">
                <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-primary']) ?>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
<?php
endif;

views/user/request.php
<?php
/**
 * @link http://zenothing.com/
*/

use app\widgets\Ext;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var $this yii\web\View
 * @var $message string
 * @var $model app\models\Password
 * @var $form ActiveForm
 */

$this->title = Yii::t('app', 'Request for password recovery');

?>
<div class="user-password">
    <?= Ext::stamp() ?>
    <h1><?= $this->title ?></h1>
    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'email') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Submit'), ['class' => 'btn btn-primary']) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>

views/user/update.php
<?php
/**
 * @link http://zenothing.com/
*/

use yii\authclient\widgets\AuthChoiceAsset;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = Yii::t('app', 'Update User') . ': ' . $model->name;
if (!Yii::$app->user->isGuest && Yii::$app->user->identity->isManager()) {
    $this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
}
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'name' => $model->name]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="user-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php
    require 'panel.php';
    ?>
    
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/user/view.php
<?php
/**
 * @link http://zenothing.com/
 */

use app\models\User;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\User */


$this->title = $model->name;
if (!Yii::$app->user->isGuest && Yii::$app->user->identity->isManager()) {
    $this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
    $this->params['breadcrumbs'][] = $this->title;
}

$columns = [
    'name',
    'email:email',
    [
        'attribute' => 'account',
        'format' => 'html',
        'value' => Html::tag('span', $model->account) . ' ' . ($model->account > 0 ? Html::a(Yii::t('app', 'Withdraw'),
                ['invoice/invoice/create', 'amount' => (int) $model->account, 'scenario' => 'withdraw'],
                ['class' => 'btn btn-success btn-xs']) : '')
    ],
    'phone',
    'skype',
    'forename',
    'surname',
    'perfect',
];

if (!Yii::$app->user->isGuest && Yii::$app->user->identity->isAdmin()) {
    $columns[] = [
        'attribute' => 'status',
        'value' => User::statuses()[$model->status]
    ];
}

$referral = Url::to(['/user/signup', 'ref_name' => $model->name], true);
?>
<div class="roompic"></div>
<div class="user-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php
    require 'panel.php';
    ?>

    <div>
        <div>
            <?php
            echo Html::a(Yii::t('app', 'Referral Link'), $referral, ['class' => 'form-label']);
            ?>

            <input class="form-control" value="<?= Url::to($referral, true); ?>">
        </div>

        <?= DetailView::widget([
            'model' => $model,
            'attributes' => $columns,
        ]) ?>
    </div>
</div>